require "./RTuple"
require "./Canvas"
require "./Matrix"
require "./Transformation"
require "./Rays"
require "./Intersection"
require "./Lights"
require "./Materials" 
require "./Patterns" 
require "./Shape"
require "./Group"
require "./Sphere"
require "./Plane"
require "./Cube"
require "./Cylinder"
require "./Cone"
require "./Triangle"
require "./World"
require "./Camera"

module RayTracer
  VERSION = "0.1.0"
end
