sphere_shadow.ppm: sphere_shadow.cr
	crystal run sphere_shadow.cr

sphere_material.ppm: sphere_material.cr
	crystal run sphere_material.cr

all : sphere_material.ppm sphere_material.ppm 

test :
	crystal spec

